### ISSUE TITLE
Drag'n'Drop image component is not working correctly

### ISSUE THREAD

**Issue by ksaitor** [cryptojobslist/frontend#16]
Example: https://submit.cryptojobslist.com/jobs/front-end-ui-ux-development-paid-internship-at-lunar-digital-assets-los-angeles/edit/fe3kp4a58at

![screen shot 2018-06-22 at 5 45 24 pm](https://user-images.githubusercontent.com/936436/41770231-3322560a-7644-11e8-87df-c9f37c4811b6.jpg)

**Comment by Kr1an** [comment]
**hotfix branch:**
https://github.com/cryptojobslist/frontend/tree/hotfix/dnd-duplication

**to add locally:**
`git flow hotfix pull dnd-duplication`

**Comment by ksaitor** [comment]
works locally. thanks!
testing in production now…

**Comment by ksaitor** [comment]
works in production too. thanks 🙌 @Kr1an
