### ISSUE TITLE
View <Link> starting acting like a relative link… not as an absolute.

### ISSUE THREAD

**Issue by ksaitor** [cryptojobslist/frontend#17]
![screen shot 2018-06-22 at 5 46 48 pm](https://user-images.githubusercontent.com/936436/41770315-5d7f99f8-7644-11e8-8654-0440dcf2966a.jpg)

Example [page](https://submit.cryptojobslist.com/jobs/front-end-ui-ux-development-paid-internship-at-lunar-digital-assets-los-angeles/edit/fe3kp4a58at)

**View** button should be (and used to be) opening
- https://cryptojobslist.com/jobs/front-end-ui-ux-development-paid-internship-at-lunar-digital-assets-los-angeles

but currently it's opening a relative path:
- https://submit.cryptojobslist.com/jobs/front-end-ui-ux-development-paid-internship-at-lunar-digital-assets-los-angeles/edit/https://cryptojobslist.com/jobs/front-end-ui-ux-development-paid-internship-at-lunar-digital-assets-los-angeles

**Comment by Kr1an** [comment]
https://github.com/cryptojobslist/frontend/tree/feature/relative-link

**Comment by ksaitor** [comment]
Done. Works. Thank you! @Kr1an 

Но, 1 час для того что бы поменять с `<Button as={Link}` на `<Button as={a}`  ?!
Это почему так? Отвлечения? Много вариантов пробывал пока дошёл до этого решения? Какая то другая причина? — Передо мной пока что отчитываться по этому вопросу не нужно (пока что). Главное что бы сам чётко понимал причины.
