### ISSUE TITLE
Support drag and drop on image uploads

### ISSUE THREAD

**Issue by ksaitor** [cryptojobslist/frontend#4]
![screen shot 2018-06-05 at 11 55 04 am](https://user-images.githubusercontent.com/936436/40954489-62e4be40-68b7-11e8-96f7-187ad7f51902.jpg)

**Comment by ksaitor** [comment]
would be good to add 
[] loading spinners on images themselves
[] highlight that image components are "droppable" when file is being dragged to them

- please try to reuse Semantic UI components as much as possible :)

**Comment by Kr1an** [comment]
https://github.com/cryptojobslist/frontend/pull/8

**Comment by ksaitor** [comment]
- [ ]  once works well on JobCreate page — reuse this in JobEdit page as well

**Comment by Kr1an** [comment]
So, why both images are loaded simultaneously. We have only one loading variable in JobStore.
New component is stateless and will show loading if we pass loading={true}. So we need to figure out the way to separate loading variable for each individual image

**Comment by ksaitor** [comment]
that's right. `loading` in `JobStore` is for `JobStore` as a whole. Not for each component individually. Might make sense to add a separate `loading` variable for each component that needs it. E.g. `loading.companyLogo`, `loading.bossPicture`, etc… just an idea. Perhaps there is a more cleaver way of doing this.

**Comment by Kr1an** [comment]
fix loading problem and boundary problem

**Comment by ksaitor** [comment]
@Kr1an feel free to close this.
Yay 🎉 Your first closed issue 👍
